VICT_FOLDER = "datasets/vict/408v/"
ENV_FOLDER = "datasets/env/94x94_408v/"

AGENT_CONFIG_FOLDER = "agents/configs/"


N_EXPLORER_AGENTS = 3
TIME_EXPLORER_LIMIT = 5000
COST_EXPLORER_LINE = 1.0
COST_EXPLORER_DIAG = 1.5
COST_EXPLORER_READ = 2.0
COST_EXPLORER_FIRST_AID = 5.0
